const SERVER_URL = "https://skill-sage-backend-njh6.onrender.com";

export const REACT_APP_SERVER_URL = SERVER_URL;
export const VITE_SERVER_URL = SERVER_URL;
export const SERVER_BASE_URL = SERVER_URL;

REACT_APP_SERVER_URL = SERVER_URL;
REACT_APP_LOCAL_BASE_URL = SERVER_URL;
REACT_APP_SERVER_BASE_URL = SERVER_URL;
